language: r

branches:
  only:
    - master
    
cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - Rscript -e "bookdown::render_book('index.Rmd')"

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  
